name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main, generic-safe-architecture-cs-2520]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:clean

      - name: Test
        run: yarn test

  size-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:clean

      - name: Test Size
        run: yarn test:size

  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          ignore-compile: true
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

  deploy-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run hardhat node in background
        run: ./node_modules/.bin/hardhat node &

      - name: check deploy
        run: yarn deploy:smoketest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Generate coverage report
        run: yarn test:coverage

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 100
