name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Build
        run: yarn install

      - name: Test
        run: cd ./smart-contract-xdai && ./node_modules/.bin/truffle test

  coverage:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Build
        run: yarn install

      - name: Generate coverage report
        run: cd ./smart-contract-xdai && ./node_modules/.bin/truffle run coverage

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./smart-contract-xdai/coverage/lcov.info"
